# Generated by Django 6.0.2 on 2026-02-14 17:12

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('genre', models.CharField(choices=[('classics', 'Classics'), ('books-we-love', 'Books We Love'), ('sci-fi', 'Sci-Fi'), ('science', 'Science'), ('history', 'History'), ('romance', 'Romance'), ('thriller', 'Thriller'), ('kids', 'Kids books')], max_length=75)),
                ('IBSN', models.DecimalField(decimal_places=0, max_digits=13)),
                ('publication_date', models.DateField()),
                ('average_rating', models.DecimalField(decimal_places=1, default=Decimal('0.0'), max_digits=3)),
            ],
        ),
    ]
