# Generated by Django 6.0.2 on 2026-02-15 08:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='image_url',
            field=models.URLField(default=0, validators=[django.core.validators.RegexValidator(message='Enter a valid URL.', regex='^(https?://)?([a-zA-Z0-9.-]+)\\.([a-zA-Z]{2,6})([/:?=&#][a-zA-Z0-9-._~:/?=&#]*)?$')]),
            preserve_default=False,
        ),
    ]
